/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { ApplicationCustomsStepFive } from './applicationCustomsStepFive';
 import { ApplicationCustomsStepOne } from './applicationCustomsStepOne';
 import { ApplicationCustomsStepTwo } from './applicationCustomsStepTwo';
 
 
 export interface Application { 
     applicationCustomsStepFive?: ApplicationCustomsStepFive;
     applicationCustomsStepOne?: ApplicationCustomsStepOne;
     applicationCustomsStepTwo?: ApplicationCustomsStepTwo;
 }