/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationAttachment } from './applicationAttachment';
import { RewardAmount } from './rewardAmount';


export interface ApplicationCustomsStepOne {
    anomalyCaptureDate?: Date;
    anomalyReason?: string;
    anomalyReportNo?: string;
    appealOrderDate?: Date;
    appealOrderNo?: string;
    applicationAttachments?: Array<ApplicationAttachment>;
    applyingOfficeOid?: string;
    billOfEntryNo?: string;
    billOfEntryDate?: string;
    category?: string;
    collectedDutyAndPenaltyAmount?: any;
    customsRewardFileNumber?: number;
    exporterImporterDutyAmount?: any;
    nbrRewardFileNumber?: number;
    officeHeadsName?: string;
    officeOid?: string;
    referenceNo?: string;
    remarksFromCustomsOffice?: string;
    rewardAmounts?: Array<RewardAmount>;
    rewardableAmount?: any;
    officeName: string;
    officeAddress: string;
    extraReceivedAmount?: any;
    applicationStatus?: string;
    applicationStatusBn?: string;
    accusedCompanyName?: string;
    accusedCompanyAddress?: string;
}
