/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OperatorRequestDTO {
    oid?: string;
    name?: string;
    officeCode?: string;
    dob?: Date;
    nidNumber?: string;
    joiningDate?: Date;
    userId?: string;
    contactNumber?: string;
    status?: string;
    password?: string,
    designation?: string,
    email?: string
}
