import {RewardAmount} from '@app/auth/application/model/rewardAmount';

/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ApplicationEntity2 {
    anomalyCaptureDate?: Date;
    anomalyReason?: string;
    anomalyReportNo?: string;
    appealOrderDate?: Date;
    appealOrderNo?: string;
    applicationDate?: Date;
    applicationNarration?: string;
    applicationStatus?: string;
    applyingOfficeOid?: string;
    billOfEntryNo?: string;
    category?: string;
    collectedDutyAndPenaltyAmount?: number;
    createdBy?: string;
    createdOn?: Date;
    customsRewardFileNumber?: number;
    exporterImporterDutyAmount?: number;
    id?: number;
    nbrRewardFileNumber?: number;
    officeHeadsName?: string;
    officeName?: string;
    officeAddress?: string;
    officeOid2?: string;
    referenceNo?: string;
    remarksFromCustomsOffice?: string;
    rewardableAmount?: number;
    suggestionFromNbr?: string;
    suggestionStatus?: string;
    totalRewardedAmount?: string;
    updatedBy?: string;
    updatedOn?: Date;
    rewardAmounts?: Array<RewardAmount>;
    extraReceivedAmount: string;
    customsAwardSanctioningCommittee: string;
}
