/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ApplicationAttachment} from './applicationAttachment';
import {RewardAmount} from './rewardAmount';


export interface ApplicationCustomsStepTwo {
    oid?: string;
    applicationNarration?: string;
    applicationDate?: Date;
    applicationAttachments: Array<ApplicationAttachment>;
    applicationStatus?: string;
    applicationStatusBn?: string;
}
