/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RewardAmount {
    advancePaidAmount?: number;
    applicationId?: string;
    appliedRewardAmount?: number;
    createdBy?: string;
    createdOn?: Date;
    designation?: string;
    employeeName?: string;
    id?: number;
    isRewarded?: string;
    rewardedAmount?: number;
    updatedBy?: string;
    updatedOn?: Date;
}
